import { existsSync, mkdirSync, writeFileSync, createWriteStream } from "fs";
import { join } from "path";
import { createHash } from "crypto";
import { tmpdir } from "os";
import { packageDir, isPackageInstalled, toSlug, ensureForgeDirs, tarballsDir } from "./store.js";
import type { PackageDetail, PackageVersion } from "./registry.js";

/**
 * Ensure ~/.forge/packages/<slug>@<version>/ exists with package content.
 * For v0.1: if tarball is reachable, download and extract; otherwise mock-generate from registry metadata.
 * Returns the source dir path.
 */
export async function ensurePackageContent(
  pkgName: string,
  version: string,
  detail: PackageDetail,
  versionMeta: PackageVersion
): Promise<string> {
  const slug = toSlug(pkgName);
  const dest = packageDir(slug, version);
  if (isPackageInstalled(slug, version)) return dest;

  ensureForgeDirs();
  if (!existsSync(dest)) mkdirSync(dest, { recursive: true });

  const tarballUrl = versionMeta.tarball;
  const sha256 = versionMeta.sha256;
  const isPlaceholder = sha256.startsWith("placeholder") || tarballUrl.includes("placeholder");

  if (!isPlaceholder) {
    try {
      await downloadAndExtract(tarballUrl, sha256, dest);
      return dest;
    } catch (err) {
      console.warn(`[forge] download failed for ${pkgName}@${version}: ${(err as Error).message}`);
      console.warn(`[forge] falling back to mock generation`);
    }
  }

  // Mock generation — create minimal package content from registry
  generateMockPackage(pkgName, version, detail, versionMeta, dest);
  return dest;
}

function generateMockPackage(
  pkgName: string,
  version: string,
  detail: PackageDetail,
  versionMeta: PackageVersion,
  dest: string
): void {
  const type = detail.type;
  // SKILL.md
  if (type === "skill" || type === "agent" || type === "command") {
    const skillName = pkgName.split("/")[1] ?? pkgName;
    const content = `# ${skillName} — ${detail.description}

> Installed via Forge v0.1 — ${pkgName}@${version}
> Source: ${detail.repository ?? detail.homepage ?? "registry"}
> Type: ${type}

## Usage
This is a mock package generated by Forge when the real tarball is not yet available.
Replace with real content when tarball download is enabled.

## Info
- Package: ${pkgName}
- Version: ${version}
- Type: ${type}
- Keywords: ${(detail.keywords ?? []).join(", ")}

## Forge
\`\`\`bash
forge info ${pkgName}
forge list
forge doctor
\`\`\`
`;
    writeFileSync(join(dest, "SKILL.md"), content);
  }

  // MCP: also write a forge-mcp.json manifest for adapter use
  if (type === "mcp" && versionMeta.mcp) {
    writeFileSync(join(dest, "forge-mcp.json"), JSON.stringify(versionMeta.mcp, null, 2));
    // also SKILL.md for discoverability
    writeFileSync(
      join(dest, "SKILL.md"),
      `# ${pkgName} — MCP Server\n\nMCP command: \`${versionMeta.mcp.command} ${(versionMeta.mcp.args ?? []).join(" ")}\`\n`
    );
  }

  // forge.toml manifest inside package (for debugging / audit)
  const manifest = `# Generated by Forge — mock package
[package]
name = "${pkgName}"
version = "${version}"
type = "${type}"
description = "${detail.description.replace(/"/g, '\\"')}"
`;
  writeFileSync(join(dest, "forge.toml"), manifest);

  // Also write .forge-meta.json for tooling
  writeFileSync(
    join(dest, ".forge-meta.json"),
    JSON.stringify({ name: pkgName, version, type, installedAt: new Date().toISOString(), tarball: versionMeta.tarball }, null, 2)
  );
}

async function downloadAndExtract(url: string, expectedSha256: string, dest: string): Promise<void> {
  const tmpFile = join(tmpdir(), `forge-${Date.now()}-${Math.random().toString(36).slice(2)}.tgz`);
  // Download
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());

  // Verify sha256
  if (expectedSha256 && !expectedSha256.startsWith("placeholder")) {
    const hash = createHash("sha256").update(buf).digest("hex");
    if (hash !== expectedSha256) {
      throw new Error(`SHA256 mismatch: expected ${expectedSha256}, got ${hash}`);
    }
  }

  // Save to cache
  const cached = join(tarballsDir(), `${url.split("/").pop()}`);
  try {
    const { writeFileSync } = await import("fs");
    writeFileSync(cached, buf);
  } catch {
    // ignore cache write fail
  }

  // Extract — try tar if available
  // We use Node's child_process to call tar (available on Windows 10+ and all Unix)
  const { execSync } = await import("child_process");
  // Write tmp file
  const { writeFileSync: wfs } = await import("fs");
  wfs(tmpFile, buf);
  try {
    execSync(`tar -xzf "${tmpFile}" -C "${dest}" --strip-components=1`, { stdio: "pipe" });
  } catch {
    // Try without strip
    try {
      execSync(`tar -xzf "${tmpFile}" -C "${dest}"`, { stdio: "pipe" });
    } catch (e) {
      throw new Error(`tar extract failed: ${(e as Error).message}`);
    }
  } finally {
    try {
      const { unlinkSync } = await import("fs");
      unlinkSync(tmpFile);
    } catch {}
  }
}

export function isPlaceholderSha(sha: string): boolean {
  return sha.startsWith("placeholder");
}
