import { existsSync, mkdirSync, writeFileSync, createWriteStream, rmSync, readFileSync } from "fs";
import { join, resolve, sep } from "path";
import { createHash } from "crypto";
import { tmpdir } from "os";
import { execFileSync } from "child_process";
import { packageDir, packagesDir, isPackageInstalled, toSlug, ensureForgeDirs, tarballsDir } from "./store.js";
import type { PackageDetail, PackageVersion } from "./registry.js";
import { signPackage, verifyPackage } from "./sign.js";

export interface EnsureContentOpts {
  /** Mock content generation is ONLY allowed with explicit opt-in (`--mock` flag).
   *  Without it, placeholder SHAs and download/verify failures are hard errors (fail-closed). */
  allowMock?: boolean;
}

/**
 * Ensure ~/.forge/packages/<slug>@<version>/ exists with package content.
 * Fail-closed: download/hash errors throw (exit-1 path in callers), partial
 * dirs are cleaned up. Mock generation requires opts.allowMock (`--mock`).
 * Returns the source dir path.
 */
export async function ensurePackageContent(
  pkgName: string,
  version: string,
  detail: PackageDetail,
  versionMeta: PackageVersion,
  opts: EnsureContentOpts = {}
): Promise<string> {
  const slug = toSlug(pkgName);
  const dest = packageDir(slug, version);
  if (isPackageInstalled(slug, version)) {
    // Empty-dir guard: a leftover/partial dir must never read as "installed".
    try {
      const { readdirSync } = await import("fs");
      if (readdirSync(dest).length > 0) return dest;
      rmSync(dest, { recursive: true, force: true });
    } catch {
      return dest;
    }
  }

  ensureForgeDirs();

  const tarballUrl = versionMeta.tarball ?? "";
  const sha256 = versionMeta.sha256 ?? "";
  const isPlaceholder = sha256.startsWith("placeholder") || tarballUrl.includes("placeholder");

  // No verified tarball in registry: mock ONLY with explicit opt-in, else hard error.
  if (isPlaceholder) {
    if (!opts.allowMock) {
      throw new Error(
        `[forge] ${pkgName}@${version} has no verified tarball yet (placeholder SHA).\n` +
        `[forge] Re-run with --mock to install mock content, or run 'forge audit' to see verification status.`
      );
    }
    console.warn(`[forge] warning: installing MOCK content for ${pkgName}@${version} (--mock)`);
    let createdMockDir = false;
    if (!existsSync(dest)) {
      mkdirSync(dest, { recursive: true });
      createdMockDir = true;
    }
    try {
      generateMockPackage(pkgName, version, detail, versionMeta, dest);
    } catch (err) {
      if (createdMockDir) {
        try {
          rmSync(dest, { recursive: true, force: true });
        } catch {}
      }
      throw err;
    }
    return dest;
  }

  // Real tarball: fail-closed. Any download/hash/extract error throws and
  // cleans up the partial dir so a half-install never reads as "installed".
  let createdDir = false;
  if (!existsSync(dest)) {
    mkdirSync(dest, { recursive: true });
    createdDir = true;
  }
  try {
    await downloadAndExtract(tarballUrl, sha256, dest, slug);
    return dest;
  } catch (err) {
    if (createdDir) {
      try {
        rmSync(dest, { recursive: true, force: true });
      } catch {}
    }
    throw new Error(
      `[forge] download/verify failed for ${pkgName}@${version}: ${(err as Error).message}\n` +
      `[forge] Nothing was installed. Re-run with --mock to install mock content instead.`
    );
  }
}

function generateMockPackage(
  pkgName: string,
  version: string,
  detail: PackageDetail,
  versionMeta: PackageVersion,
  dest: string
): void {
  const type = detail.type;
  const skillName = pkgName.split("/")[1] ?? pkgName;
  // Faz 11: her tip gerçek iskelet üretir — forge add her tipi doğru yere kurar
  if (type === "skill") {
    const content = `# ${skillName} — ${detail.description}

> Installed via Forge v0.1 — ${pkgName}@${version}
> Source: ${detail.repository ?? detail.homepage ?? "registry"}
> Type: ${type}

## Usage
This is a mock package generated by Forge when the real tarball is not yet available.
Replace with real content when tarball download is enabled.

## Info
- Package: ${pkgName}
- Version: ${version}
- Type: ${type}
- Keywords: ${(detail.keywords ?? []).join(", ")}

## Forge
\`\`\`bash
forge info ${pkgName}
forge list
forge doctor
\`\`\`
`;
    writeFileSync(join(dest, "SKILL.md"), content);
  }

  if (type === "agent") {
    writeFileSync(join(dest, "agent.md"), `# ${skillName} — ${detail.description}\n\n> Installed via Forge — ${pkgName}@${version}\n\nDefine your agent's system prompt here.\n`);
    writeFileSync(join(dest, "SKILL.md"), `# ${skillName} — agent\n\nSee agent.md for system prompt.\n`);
  }

  if (type === "command") {
    writeFileSync(join(dest, "command.md"), `# ${skillName} — ${detail.description}\n\n> Installed via Forge — ${pkgName}@${version}\n\nSlash command: /${skillName}\n`);
  }

  if (type === "hook") {
    writeFileSync(join(dest, "hook.json"), JSON.stringify({ name: pkgName, hooks: { "pre-tool": { entry: "./hook.js" } } }, null, 2) + "\n");
    writeFileSync(join(dest, "hook.js"), `// ${pkgName} hook entry\nmodule.exports = {};\n`);
  }

  if (type === "plugin") {
    writeFileSync(join(dest, "plugin.json"), JSON.stringify({ name: skillName, entry: "index.js", hooks: ["pre-tool", "post-tool"] }, null, 2) + "\n");
    writeFileSync(join(dest, "index.js"), `// ${pkgName} plugin entry\nmodule.exports = {};\n`);
  }

  // MCP: also write a forge-mcp.json manifest for adapter use (Faz 11: mcp.json dahil)
  if (type === "mcp" && versionMeta.mcp) {
    writeFileSync(join(dest, "forge-mcp.json"), JSON.stringify(versionMeta.mcp, null, 2));
    writeFileSync(join(dest, "mcp.json"), JSON.stringify({ mcpServers: { [skillName]: versionMeta.mcp } }, null, 2) + "\n");
    // also SKILL.md for discoverability
    writeFileSync(
      join(dest, "SKILL.md"),
      `# ${pkgName} — MCP Server\n\nMCP command: \`${versionMeta.mcp.command} ${(versionMeta.mcp.args ?? []).join(" ")}\`\n`
    );
  }

  // forge.toml manifest inside package (for debugging / audit)
  const manifest = `# Generated by Forge — mock package
[package]
name = "${pkgName}"
version = "${version}"
type = "${type}"
description = "${detail.description.replace(/"/g, '\\"')}"
`;
  writeFileSync(join(dest, "forge.toml"), manifest);

  // Also write .forge-meta.json for tooling
  writeFileSync(
    join(dest, ".forge-meta.json"),
    JSON.stringify({ name: pkgName, version, type, installedAt: new Date().toISOString(), tarball: versionMeta.tarball }, null, 2)
  );

  // Fail-closed marker: lets `forge audit` / `forge doctor` distinguish mock
  // content from verified installs. Never write this for real tarballs.
  writeFileSync(
    join(dest, ".forge-mock"),
    JSON.stringify({ mock: true, name: pkgName, version, installedAt: new Date().toISOString() }, null, 2) + "\n"
  );
}

async function downloadAndExtract(url: string, expectedSha256: string, dest: string, slug: string): Promise<void> {
  // Path-escape guard: dest must stay inside the packages store.
  const storeRoot = resolve(packagesDir()) + sep;
  if (!resolve(dest).startsWith(storeRoot)) {
    throw new Error(`refusing to extract outside packages dir: ${dest}`);
  }
  const tmpFile = join(tmpdir(), `forge-${process.pid}-${Date.now()}-${Math.random().toString(36).slice(2)}.tgz`);
  
  // Prefer gh CLI for GitHub release assets (handles auth/redirects).
  if (url.includes("github.com") && url.includes("/releases/download/")) {
    try {
      execFileSync("gh", ["release", "download", "--repo", "oomerevren-beep/forge", "--pattern", "*.tar.gz", "-D", tmpdir(), "--clobber"], { stdio: "pipe" });
      // Find the downloaded file
      const { readdirSync } = await import("fs");
      const files = readdirSync(tmpdir()).filter(f => f.endsWith(".tar.gz") && f.startsWith(slug));
      if (files.length > 0) {
        const downloaded = join(tmpdir(), files[0]);
        const buf = readFileSync(downloaded);
        const sha256 = createHash("sha256").update(buf).digest("hex");
        if (sha256 !== expectedSha256) {
          throw new Error(`sha256 mismatch: expected ${expectedSha256}, got ${sha256}`);
        }
        // Use Python tarfile for extraction (works reliably on Windows + Unix)
        // Epoch 1e: filter='data' prevents tar-slip (../ path traversal) and symlink escapes
        execFileSync("python", ["-c", `
import tarfile, os, sys
with tarfile.open(sys.argv[1], 'r:gz') as tf:
    tf.extractall(sys.argv[2], filter='data')
`, downloaded, dest], { stdio: "pipe" });
        rmSync(downloaded, { force: true });
        return;
      }
    } catch (e) {
      // fall through to fetch fallback
    }
  }
  
  // Fallback: fetch (works for public URLs without auth)
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());

  // Verify sha256
  if (expectedSha256 && !expectedSha256.startsWith("placeholder")) {
    const hash = createHash("sha256").update(buf).digest("hex");
    if (hash !== expectedSha256) {
      throw new Error(`SHA256 mismatch: expected ${expectedSha256}, got ${hash}`);
    }
  }

  // Save to cache (filename namespaced by slug to avoid collisions across scopes)
  const rawName = url.split("/").pop() || "package.tgz";
  const safeName = rawName.replace(/[^a-zA-Z0-9._-]/g, "_");
  const cached = join(tarballsDir(), `${slug}--${safeName}`);
  try {
    const { writeFileSync } = await import("fs");
    writeFileSync(cached, buf);
  } catch {
    // ignore cache write fail
  }

  // Write to temp file for extraction
  const { writeFileSync: wfs } = await import("fs");
  wfs(tmpFile, buf);

  // Extract via Python tarfile (works reliably on Windows + Unix)
  // Epoch 1e: filter='data' prevents tar-slip (../ path traversal) and symlink escapes
  try {
    execFileSync("python", ["-c", `
import tarfile, os, sys
with tarfile.open(sys.argv[1], 'r:gz') as tf:
    tf.extractall(sys.argv[2], filter='data')
`, tmpFile, dest], { stdio: "pipe" });
  } catch (e) {
    throw new Error(`tar extract failed: ${(e as Error).message}`);
  } finally {
    try {
      const { unlinkSync } = await import("fs");
      unlinkSync(tmpFile);
    } catch {}
  }

  // Defense-in-depth: filter='data' already strips symlinks and ../ escapes,
  // but we verify post-extraction as a safety net.
  await assertNoSymlinks(dest);
}

/** Walk dest; throw on any symlink entry OR path that escapes the dest root.
 *  Epoch 1e: symlinks that stay WITHIN the dest dir are safe (GitHub archives use them). */
async function assertNoSymlinks(dest: string): Promise<void> {
  const { readdirSync, lstatSync, realpathSync, readlinkSync } = await import("fs");
  const destReal = realpathSync(dest);
  const stack: string[] = [dest];
  while (stack.length > 0) {
    const dir = stack.pop() as string;
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      const stat = lstatSync(full);
      if (stat.isSymbolicLink()) {
        // Epoch 1e: allow symlinks that resolve within the package dir (GitHub archives)
        try {
          const linkTarget = readlinkSync(full);
          const resolved = realpathSync(full);
          if (!resolved.startsWith(destReal + sep) && resolved !== destReal) {
            throw new Error(`tarball symlink escapes package dir: ${entry.name} → ${linkTarget}`);
          }
        } catch (e) {
          if ((e as Error).message?.includes("escapes")) throw e;
          // If we can't resolve, refuse
          throw new Error(`tarball contains unresolvable symlink (${entry.name}) — refusing to install`);
        }
      } else {
        // Epoch 1e: verify resolved path stays within dest (anti-tar-slip)
        try {
          const fullReal = realpathSync(full);
          if (!fullReal.startsWith(destReal + sep) && fullReal !== destReal) {
            throw new Error(`tarball entry escapes package dir: ${entry.name}`);
          }
        } catch (e) {
          if ((e as Error).message?.includes("escapes")) throw e;
        }
        if (stat.isDirectory()) stack.push(full);
      }
    }
  }
}

export function isPlaceholderSha(sha: string): boolean {
  return sha.startsWith("placeholder");
}
