import { existsSync, readFileSync, writeFileSync } from "fs";
import { join, resolve } from "path";
import { parse } from "smol-toml";

export interface LockEntry {
  name: string;
  version: string;
  type: string;
}

export interface ForgeLock {
  packages: LockEntry[];
}

export function lockPath(cwd = process.cwd()): string {
  return join(resolve(cwd), "forge.lock");
}

export function readLock(cwd = process.cwd()): ForgeLock | null {
  const p = lockPath(cwd);
  if (!existsSync(p)) return null;
  try {
    const raw = readFileSync(p, "utf-8");
    const parsed = parse(raw) as Record<string, unknown>;
    const pkgs = parsed.packages as unknown;
    if (!Array.isArray(pkgs)) return null;
    const packages: LockEntry[] = (pkgs as Record<string, unknown>[]).map((x) => ({
      name: String(x.name),
      version: String(x.version),
      type: String(x.type ?? "skill"),
    }));
    return { packages };
  } catch {
    return null;
  }
}

export function writeLock(entries: LockEntry[], cwd = process.cwd()): void {
  const p = lockPath(cwd);
  // smol-toml stringify doesn't support array-of-tables well via object; craft manually
  // Use [[packages]] TOML array of tables
  const lines: string[] = ['# Generated by Forge — do not edit manually', ''];
  for (const e of entries) {
    lines.push("[[packages]]");
    lines.push(`name = "${e.name}"`);
    lines.push(`version = "${e.version}"`);
    lines.push(`type = "${e.type}"`);
    lines.push("");
  }
  writeFileSync(p, lines.join("\n"));
}
