import { existsSync, readFileSync, writeFileSync } from "fs";
import { join, resolve } from "path";
import { parse } from "smol-toml";
import { loadPackageDetail } from "./registry.js";

export interface LockEntry {
  name: string;
  version: string;
  type: string;
  /** Where the bits came from (registry tarball URL). Empty for mock installs. */
  tarball?: string;
  /** SHA-256 integrity hash pinned at resolve time. */
  sha256?: string;
  /** Registry source id (default: bundled registry). */
  source?: string;
}

export interface ForgeLock {
  packages: LockEntry[];
}

/** Build a lock entry with pinned integrity (source URL + sha256). */
export function lockEntryFor(
  name: string,
  version: string,
  type: string,
  meta: { tarball?: string; sha256?: string },
  source = "registry",
): LockEntry {
  return {
    name,
    version,
    type,
    ...(meta.tarball ? { tarball: meta.tarball } : {}),
    ...(meta.sha256 ? { sha256: meta.sha256 } : {}),
    source,
  };
}

export function lockPath(cwd = process.cwd()): string {
  return join(resolve(cwd), "forge.lock");
}

function toEntry(x: Record<string, unknown>): LockEntry {
  const entry: LockEntry = {
    name: String(x.name),
    version: String(x.version),
    type: String(x.type ?? "skill"),
  };
  if (typeof x.tarball === "string" && x.tarball.length > 0) entry.tarball = x.tarball;
  if (typeof x.sha256 === "string" && x.sha256.length > 0) entry.sha256 = x.sha256;
  if (typeof x.source === "string" && x.source.length > 0) entry.source = x.source;
  return entry;
}

export function readLock(cwd = process.cwd()): ForgeLock | null {
  const p = lockPath(cwd);
  if (!existsSync(p)) return null;
  try {
    const raw = readFileSync(p, "utf-8");
    const parsed = parse(raw) as Record<string, unknown>;
    const pkgs = parsed.packages as unknown;
    if (!Array.isArray(pkgs)) return null;
    const packages: LockEntry[] = (pkgs as Record<string, unknown>[]).map(toEntry);
    return { packages };
  } catch {
    return null;
  }
}

function escapeTomlString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Deterministic writer: entries sorted by name, fixed field order, LF only. */
export function writeLock(entries: LockEntry[], cwd = process.cwd()): void {
  const p = lockPath(cwd);
  // smol-toml stringify doesn't support array-of-tables well via object; craft manually
  // Use [[packages]] TOML array of tables
  const sorted = [...entries].sort((a, b) => a.name.localeCompare(b.name));
  const lines: string[] = ["# Generated by Forge — do not edit manually", ""];
  for (const e of sorted) {
    lines.push("[[packages]]");
    lines.push(`name = "${escapeTomlString(e.name)}"`);
    lines.push(`version = "${escapeTomlString(e.version)}"`);
    lines.push(`type = "${escapeTomlString(e.type)}"`);
    if (e.tarball) lines.push(`tarball = "${escapeTomlString(e.tarball)}"`);
    if (e.sha256) lines.push(`sha256 = "${escapeTomlString(e.sha256)}"`);
    if (e.source) lines.push(`source = "${escapeTomlString(e.source)}"`);
    lines.push("");
  }
  writeFileSync(p, lines.join("\n"));
}

export interface IntegrityIssue {
  name: string;
  kind: "yanked" | "hash-mismatch" | "unverified";
  message: string;
}

/**
 * Security barrier for --frozen installs. For every locked entry:
 * - the locked version must still exist in the registry (else "yanked")
 * - a locked real sha256 must equal the registry sha256 (else "hash-mismatch")
 * - a placeholder/mock sha256 is reported as "unverified" (fatal unless
 *   the caller explicitly allows mock via opts.allowMock)
 * Returns the issue list (empty = lock is trustworthy). Never throws on
 * registry I/O — transport failures surface as yanked with the cause inline.
 */
export async function verifyLockIntegrity(
  lock: ForgeLock,
  opts: { allowMock?: boolean } = {},
): Promise<IntegrityIssue[]> {
  const issues: IntegrityIssue[] = [];
  for (const entry of lock.packages) {
    let detail;
    try {
      detail = await loadPackageDetail(entry.name);
    } catch (e) {
      issues.push({
        name: entry.name,
        kind: "yanked",
        message: `${entry.name}: registry read failed (${(e as Error).message}) — refusing frozen install`,
      });
      continue;
    }
    const meta = detail.versions[entry.version] as
      | { tarball?: string; sha256?: string; verified?: boolean }
      | undefined;
    if (!meta) {
      issues.push({
        name: entry.name,
        kind: "yanked",
        message: `${entry.name}@${entry.version} is yanked (version missing from registry) — refusing frozen install`,
      });
      continue;
    }
    const lockedSha = entry.sha256 ?? "";
    const registrySha = meta.sha256 ?? "";
    const lockedIsPlaceholder = lockedSha.startsWith("placeholder") || lockedSha === "";
    if (lockedIsPlaceholder && !opts.allowMock) {
      issues.push({
        name: entry.name,
        kind: "unverified",
        message: `${entry.name}@${entry.version} has no pinned integrity hash — refusing frozen install (re-run without --frozen, or pass --mock to allow mock content)`,
      });
      continue;
    }
    if (!lockedIsPlaceholder && registrySha !== "" && lockedSha !== registrySha) {
      issues.push({
        name: entry.name,
        kind: "hash-mismatch",
        message: `${entry.name}@${entry.version} integrity mismatch: lock=${lockedSha.slice(0, 12)}… registry=${registrySha.slice(0, 12)}… — refusing frozen install`,
      });
    }
  }
  return issues;
}
