import { existsSync, mkdirSync, writeFileSync } from "fs";
import { join, resolve, basename, sep } from "path";

type PkgType = "skill" | "mcp" | "agent" | "command" | "hook" | "plugin";

const TEMPLATES: Record<PkgType, { forgeToml: (name: string) => string; extraFiles: (name: string) => Record<string, string> }> = {
  skill: {
    forgeToml: (name) => {
      const short = name.split("/")[1] ?? name;
      return `[package]\nname = "${name}"\nversion = "0.1.0"\ntype = "skill"\ndescription = "A new Forge skill — describe what it does"\nlicense = "MIT"\n\n[engines]\nclaude-code = "*"\n\n[skill]\nname = "${short}"\ninvocation = "/${short}"\nallowed-tools = ["Read", "Write", "Bash"]\n`;
    },
    extraFiles: (name) => ({
      "SKILL.md": `# ${name}\n\nA Forge skill. Replace this with your skill prompt.\n\n## Usage\n\nDescribe when Muse should use this skill.\n\n## Instructions\n\n- Step 1: ...\n- Step 2: ...\n`,
    }),
  },
  mcp: {
    forgeToml: (name) => `[package]\nname = "${name}"\nversion = "0.1.0"\ntype = "mcp"\ndescription = "A new MCP server"\nlicense = "MIT"\n\n[mcp]\ncommand = "node"\nargs = ["./dist/index.js"]\n`,
    extraFiles: (name) => ({
      "src/index.ts": `#!/usr/bin/env node\n// ${name} — MCP server scaffold\nconsole.log("MCP server: ${name}");\n`,
      "mcp.json": JSON.stringify({ mcpServers: { [name.split("/")[1] ?? name]: { command: "node", args: ["./dist/index.js"] } } }, null, 2) + "\n",
      "README.md": `# ${name}\n\nMCP server scaffold generated by \`forge init\`.\n`,
    }),
  },
  agent: {
    forgeToml: (name) => `[package]\nname = "${name}"\nversion = "0.1.0"\ntype = "agent"\ndescription = "A new Forge agent"\nlicense = "MIT"\n\n[agent]\nmodel = "claude-sonnet-4"\ntools = ["Read", "Write", "Bash"]\nprompt = "agent.md"\n`,
    extraFiles: (name) => ({
      "agent.md": `# ${name} — Agent\n\nDefine your agent's system prompt here.\n`,
    }),
  },
  command: {
    forgeToml: (name) => {
      const short = name.split("/")[1] ?? name;
      return `[package]\nname = "${name}"\nversion = "0.1.0"\ntype = "command"\ndescription = "A new Forge command"\nlicense = "MIT"\n\n[command]\nname = "${short}"\ninvocation = "/${short}"\n`;
    },
    extraFiles: (name) => ({
      "command.md": `# ${name} — Command\n\nDefine the slash command here.\n`,
    }),
  },
  hook: {
    forgeToml: (name) => `[package]\nname = "${name}"\nversion = "0.1.0"\ntype = "hook"\ndescription = "A new Forge hook"\nlicense = "MIT"\n\n[hook]\nevent = "pre-tool"\nentry = "hook.json"\n`,
    extraFiles: (name) => ({
      "hook.json": JSON.stringify({ name, hooks: { "pre-tool": { entry: "./hook.js" } } }, null, 2) + "\n",
    }),
  },
  plugin: {
    forgeToml: (name) => `[package]\nname = "${name}"\nversion = "0.1.0"\ntype = "plugin"\ndescription = "A new Forge plugin"\nlicense = "MIT"\n\n[plugin]\nentry = "index.js"\nhooks = ["pre-tool", "post-tool"]\n`,
    extraFiles: () => ({
      "plugin.json": JSON.stringify({ name: "plugin", entry: "index.js", hooks: ["pre-tool", "post-tool"] }, null, 2) + "\n",
      "index.js": `// Forge plugin entry\nmodule.exports = {};\n`,
      "README.md": "# Plugin scaffold\n",
    }),
  },
};

export async function runInit(opts: { name?: string; type?: string; yes?: boolean; force?: boolean; cwd?: string }): Promise<void> {
  const cwd = resolve(opts.cwd ?? process.cwd());
  const rawName = opts.name ?? basename(cwd);
  const pkgName = normalizeName(rawName);
  const type = (opts.type ?? "skill") as PkgType;
  if (!TEMPLATES[type]) {
    console.error(`[forge] unknown type "${type}" — choose: ${Object.keys(TEMPLATES).join(", ")}`);
    process.exit(1);
  }
  // If name implies a path (e.g. my-skill), create that dir under cwd
  const targetDir = opts.name ? join(cwd, opts.name) : cwd;
  const forgeTomlPath = join(targetDir, "forge.toml");

  if (existsSync(forgeTomlPath) && !opts.force) {
    console.error(`[forge] ${forgeTomlPath} already exists — use --force to overwrite`);
    process.exit(1);
  }
  if (!existsSync(targetDir)) mkdirSync(targetDir, { recursive: true });

  const tpl = TEMPLATES[type];
  const tomlContent = tpl.forgeToml(pkgName);
  writeFileSync(forgeTomlPath, tomlContent);

  const extras = tpl.extraFiles(pkgName);
  for (const [rel, content] of Object.entries(extras)) {
    const full = join(targetDir, rel);
    // ensure parent
    mkdirSync(join(targetDir, ...rel.split("/").slice(0, -1)), { recursive: true });
    if (!existsSync(full) || opts.force) writeFileSync(full, content);
  }

  const relDir = targetDir === cwd ? "." : opts.name!;
  console.log(`[forge] ✓ created ${relDir}/forge.toml [${type}]`);
  if (Object.keys(extras).length) console.log(`[forge]   + ${Object.keys(extras).join(", ")}`);
  console.log(`[forge] next: edit forge.toml & SKILL.md, then 'forge publish' (Faz 8)`);
}

function normalizeName(input: string): string {
  // allow my-skill -> my-skill/my-skill ? We expect scope/name
  // If input contains /, keep; otherwise treat as unscoped and prefix with local scope?
  // For scaffold we use "local/<name>" if no slash? But spec expects scope/name — use "local/<name>" fallback?
  // Simpler: if no slash, use "<name>/<name>" is weird. Use input as-is if it has /, else input (consumer scaffold may be folder name)
  // Forge init in a project folder without scope — keep as input; for package scaffold we need scope/name.
  // We'll produce scope/name: if input has /, use it; else `local/${input}`
  if (input.includes("/")) return input;
  // If it's a simple name like my-skill, make it local/my-skill
  if (/^[a-z0-9-]+$/.test(input)) return `local/${input}`;
  return input;
}
